version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DB=db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=somepassword
    ports:
      - "8000:8000"
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=somepassword